### PR TITLE
add thresholds utility

### PR DESCRIPTION
**Pull request by corentincarton**
Adding the thresholds script that we used to compute the return period thresholds for EFAS 5.0 and GloFAS 4.0.

### CODE REVIEW

**Review by doc78 — APPROVED** [review]

**Review by doc78 — APPROVED** [review]
Maybe we can add a unit test for thresholds?

**Review by StefaniaGrimaldi — COMMENTED** [review]
Hi @corentincarton,
thanks for preparing and uploading the python code!
I suggest adapting the readme file to reflect these edits.
Please let me know if I can help!

**Comment by corentincarton** [comment]
@doc78 and @StefaniaGrimaldi, I'll add a unit test and update the Readme. I still need to remove the legacy folder as well.

**Comment by corentincarton** [comment]
@doc78 and @StefaniaGrimaldi, I updated the readme and added some unit tests. Don't hesitate to tell me if something's missing!

**Review by StefaniaGrimaldi — APPROVED** [review]
Hi @corentincarton, thanks for adding the unit tests and some edits to the readme. Could you please also provide the technical details and replace the now-outdated section of the readme: https://github.com/ec-jrc/lisflood-utilities/tree/feature/thresholds#gfit ? 
The new section "thresholds" should include basic instructions: input, output, how-to-use (similarly to what is done for the other utilities). If you could add the technical pieces of information above, it would be great. If you wish, I can then complement the section with references to the papers used to prepare the methodology.

**Review by StefaniaGrimaldi — APPROVED** [review]
Thanks @corentincarton!

Since LISFLOOD does not provide yearly maximum as output variable, we could suggest to post-process the dis.nc LISFLOOD output file using CDO.

Please see below my proposal:

"Usage
The tool takes as input a Netcdf file containing the annual maxima of the discharge signal. LISFLOOD computes time series of discharge values (average value over the selected computational time step). The users are therefore required to compute the annual maxima.  As an example, this step can be achieved by using CDO (cdo yearmax), for all the details please refer to https://code.mpimet.mpg.de/projects/cdo/embedded/index.html#x1-190001.2.5"

What do you think?

**Comment by corentincarton** [comment]
Yes, I agree! I didn’t put that in the script as for massive dataset, it becomes a challenge.
________________________________

**Review by doc78 — APPROVED** [review]

**Pull request merged**
